language: scala
sudo: true
install: true
before_script:
  - sudo sysctl -w vm.max_map_count=262144
  
addons:
  sonarcloud:
    organization: "amitnema-github"

jdk:
  - oraclejdk8

script:
  - mvn clean site sonar:sonar

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
